sonar.projectKey=rabarijoy_MediaTekDocuments
sonar.organization=rabarijoy
sonar.host.url=https://sonarcloud.io
sonar.token=bd12cc2f559f5e3f7428b6c605a9b4da9fa75dd0

sonar.sources=MediaTekDocuments
sonar.tests=MediaTekDocuments.Tests
sonar.language=cs

sonar.exclusions=MediaTekDocuments/bin/**,MediaTekDocuments/obj/**,MediaTekDocuments/Properties/Resources.Designer.cs,MediaTekDocuments/Properties/Settings.Designer.cs,MediaTekDocuments/view/*.Designer.cs

sonar.test.inclusions=MediaTekDocuments.Tests/**/*.cs